on:
  push:
    paths:
      - "changelog/config.env"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.9'

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run linters
        run: |
          pre-commit run --all-files

  build:
    name: Build binary
    runs-on: ubuntu-latest
    needs: run-linters

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Build binaries
        run: go build

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Get release version
        id: release_version
        run: |
          . changelog/config.env

          RELEASE_DESCRIPTION=changelog/release-$RELEASE_VERSION.md
          if ! [ -f "$RELEASE_DESCRIPTION" ]; then
            echo "ERROR: missing $RELEASE_DESCRIPTION" >&2
            exit 1
          fi

          echo "::set-output name=release_version::$RELEASE_VERSION"
          echo "::set-output name=release_description::$RELEASE_DESCRIPTION"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.release_version.outputs.release_version }}
          bodyFile: ${{ steps.release_version.outputs.release_description }}
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
